
title: Escalante
version: 0.1.0

profiles:
  development:
    disqus_developer: true
#  staging:
#    base_url: http://staging.escalante.io/
#    deploy:
#      host: escalante.io
#      path: /var/www/domains/escalante.io/staging/htdocs/
#  production:
#    base_url: http://escalante.io/
#    deploy:
#      host: escalante.io
#      path: /var/www/domains/escalante.io/www/htdocs/

disqus: escalante

# google_analytics:
